# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/auth.AuthService/RegisterUser',
                request_serializer=auth__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.RegisterAdmin = channel.unary_unary(
                '/auth.AuthService/RegisterAdmin',
                request_serializer=auth__pb2.RegisterAdminRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.VerifyAccountWithOTP = channel.unary_unary(
                '/auth.AuthService/VerifyAccountWithOTP',
                request_serializer=auth__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CheckUsername = channel.unary_unary(
                '/auth.AuthService/CheckUsername',
                request_serializer=auth__pb2.CheckUsernameRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckUsernameResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/auth.AuthService/ForgotPassword',
                request_serializer=auth__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/auth.AuthService/ResetPassword',
                request_serializer=auth__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetPendingAdmins = channel.unary_unary(
                '/auth.AuthService/GetPendingAdmins',
                request_serializer=auth__pb2.EmptyRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminListResponse.FromString,
                _registered_method=True)
        self.ApproveAdmin = channel.unary_unary(
                '/auth.AuthService/ApproveAdmin',
                request_serializer=auth__pb2.AdminApprovalRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.SuspendUser = channel.unary_unary(
                '/auth.AuthService/SuspendUser',
                request_serializer=auth__pb2.UserActionRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.UnsuspendUser = channel.unary_unary(
                '/auth.AuthService/UnsuspendUser',
                request_serializer=auth__pb2.UserActionRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.LoginWithOAuth = channel.unary_unary(
                '/auth.AuthService/LoginWithOAuth',
                request_serializer=auth__pb2.LoginWithOAuthRequest.SerializeToString,
                response_deserializer=auth__pb2.LoginResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Service
    """

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAccountWithOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingAdmins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsuspendUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginWithOAuth(self, request, context):
        """OAuth login endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=auth__pb2.RegisterUserRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'RegisterAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAdmin,
                    request_deserializer=auth__pb2.RegisterAdminRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'VerifyAccountWithOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAccountWithOTP,
                    request_deserializer=auth__pb2.VerifyOTPRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginRequest.FromString,
                    response_serializer=auth__pb2.LoginResponse.SerializeToString,
            ),
            'CheckUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsername,
                    request_deserializer=auth__pb2.CheckUsernameRequest.FromString,
                    response_serializer=auth__pb2.CheckUsernameResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=auth__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=auth__pb2.ResetPasswordRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'GetPendingAdmins': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingAdmins,
                    request_deserializer=auth__pb2.EmptyRequest.FromString,
                    response_serializer=auth__pb2.AdminListResponse.SerializeToString,
            ),
            'ApproveAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAdmin,
                    request_deserializer=auth__pb2.AdminApprovalRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'SuspendUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendUser,
                    request_deserializer=auth__pb2.UserActionRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'UnsuspendUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsuspendUser,
                    request_deserializer=auth__pb2.UserActionRequest.FromString,
                    response_serializer=auth__pb2.AuthResponse.SerializeToString,
            ),
            'LoginWithOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginWithOAuth,
                    request_deserializer=auth__pb2.LoginWithOAuthRequest.FromString,
                    response_serializer=auth__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Service
    """

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RegisterUser',
            auth__pb2.RegisterUserRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RegisterAdmin',
            auth__pb2.RegisterAdminRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAccountWithOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/VerifyAccountWithOTP',
            auth__pb2.VerifyOTPRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Login',
            auth__pb2.LoginRequest.SerializeToString,
            auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CheckUsername',
            auth__pb2.CheckUsernameRequest.SerializeToString,
            auth__pb2.CheckUsernameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ForgotPassword',
            auth__pb2.ForgotPasswordRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ResetPassword',
            auth__pb2.ResetPasswordRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingAdmins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetPendingAdmins',
            auth__pb2.EmptyRequest.SerializeToString,
            auth__pb2.AdminListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ApproveAdmin',
            auth__pb2.AdminApprovalRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SuspendUser',
            auth__pb2.UserActionRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsuspendUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UnsuspendUser',
            auth__pb2.UserActionRequest.SerializeToString,
            auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginWithOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/LoginWithOAuth',
            auth__pb2.LoginWithOAuthRequest.SerializeToString,
            auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
